### ISSUE TITLE
Question: Is there any way to cleany generate bytecode?

### ISSUE THREAD

**Issue by 64kramsystem** [tenderlove/tenderjit#18]
Is there any way to cleanly generate bytecode (along with the required data structures, e.g. local table etc)?

Currently, the unit testing of the instructions is not unit testing in a strict sense - it's actually more functional (IMO), as each unit tests performs more work than just just creating and executing an instruction.

If bytecode could be cleanly/easily generated, there would be several benefits:

- tests would be targeted and evident; right now, the actual instructions are hidden behind an abstraction
- tested behavior would actually be guaranteed; due to the abstraction, it's technically possible that the compiler, at some point, compiles to different instructions, causing the test to actually test something different
- debugging could be easier, due to the lower amount of instructions.

On the other hand, the instructions testings works fine as it is; this is more of a generic discussion :)

Also, what do you think of enabling discussions on this repository? It would allow users to make generic questions (e.g. "which resources to study on :grimacing:") separate from issues in a strict sense.

That's my 2 bits, anyway :laughing:

**Comment by tenderlove** [comment]
AFAIK there isn't any way to test just one bytecode.  Also I'm not totally sure how we'd do it.  For example the `leave` instruction doesn't make sense on its own, it needs another instruction to push something on the stack.  One thing I was thinking [MJIT](https://github.com/ruby/ruby/blob/27d9935d516a77a7b8c245398befd8b2dd059dcd/test/ruby/test_jit.rb) and [YJIT](https://github.com/Shopify/yjit/blob/3df3fb0692072b5508c27852b9680bc8ca6e8393/test/ruby/test_yjit.rb) both have tests for particular instructions.  Maybe there is a way we could reuse those tests, or combine them or something.  I think it would be useful if we had a generic "test suite for JITs".

> Also, what do you think of enabling discussions on this repository? It would allow users to make generic questions (e.g. "which resources to study on 😬") separate from issues in a strict sense.

Enabling discussions sounds great!  I went ahead and did that.  We can move this to a discussion. 😄
