### ISSUE TITLE
bundle install fails since worf repository's default branch is main

### ISSUE THREAD

**Issue by mohsen-alizadeh** [tenderlove/tenderjit#25]
```
$ bundle install
Fetching https://github.com/ruby/fiddle.git
Fetching https://github.com/tenderlove/worf.git
fatal: Needed a single revision
Revision master does not exist in the repository https://github.com/tenderlove/worf.git. Maybe you misspelled it?`
```

need to specify the main branch in gemfile

**Comment by 64kramsystem** [comment]
Interesting. I don't experience this problem:

```
/path/to/tenderjit(4f4b76b)$ bx rake test
https://github.com/tenderlove/worf.git is not yet checked out. Run `bundle install` first.

/path/to/tenderjit(4f4b76b)$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/.......
Fetching https://github.com/tenderlove/worf.git
Using rake 13.0.6
Using bindata 2.4.10
Using elftools 1.1.3
Using byebug 11.1.3
Using ffi 1.15.4
Using minitest 5.14.4
Using crabstone 4.0.3
Using bundler 2.2.22
Using worf 1.0.0 from https://github.com/tenderlove/worf.git (at main@5957198)
Using fiddle 1.1.0 from https://github.com/ruby/fiddle.git (at master@f52b0e4)
Using odinflex 1.0.0
Using fisk 2.3.0 from https://github.com/tenderlove/fisk.git (at main@fc70d6d)
Using tenderjit 1.0.0 from source at `.`
Bundle complete! 8 Gemfile dependencies, 13 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by mohsen-alizadeh** [comment]
> Interesting. I don't experience this problem:
> 
> ```
> /path/to/tenderjit(4f4b76b)$ bx rake test
> https://github.com/tenderlove/worf.git is not yet checked out. Run `bundle install` first.
> 
> /path/to/tenderjit(4f4b76b)$ bundle install
> Fetching gem metadata from https://rubygems.org/
> Fetching gem metadata from https://rubygems.org/.......
> Fetching https://github.com/tenderlove/worf.git
> Using rake 13.0.6
> Using bindata 2.4.10
> Using elftools 1.1.3
> Using byebug 11.1.3
> Using ffi 1.15.4
> Using minitest 5.14.4
> Using crabstone 4.0.3
> Using bundler 2.2.22
> Using worf 1.0.0 from https://github.com/tenderlove/worf.git (at main@5957198)
> Using fiddle 1.1.0 from https://github.com/ruby/fiddle.git (at master@f52b0e4)
> Using odinflex 1.0.0
> Using fisk 2.3.0 from https://github.com/tenderlove/fisk.git (at main@fc70d6d)
> Using tenderjit 1.0.0 from source at `.`
> Bundle complete! 8 Gemfile dependencies, 13 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
> ```
Because you have the lockfile

**Comment by 64kramsystem** [comment]
I've tried removing it, and Bundler still installs successfully:

```
/path/to/tenderjit(4f4b76b)$ bundle exec gem list
The git source https://github.com/ruby/fiddle.git is not yet checked out. Please run `bundle install` before trying to start your application

/path/to/tenderjit(4f4b76b)$ bundle install
Fetching https://github.com/ruby/fiddle.git
Fetching https://github.com/tenderlove/worf.git
Fetching https://github.com/tenderlove/fisk.git
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using rake 13.0.6
Using bindata 2.4.10
Using bundler 2.2.22
Using byebug 11.1.3
Using ffi 1.15.4
Using minitest 5.14.4
Using odinflex 1.0.0
Using crabstone 4.0.3
Using elftools 1.1.3
Using worf 1.0.0 from https://github.com/tenderlove/worf.git (at main@5957198)
Using fiddle 1.1.0 from https://github.com/ruby/fiddle.git (at master@f52b0e4)
Using fisk 2.3.0 from https://github.com/tenderlove/fisk.git (at main@fc70d6d)
Using tenderjit 1.0.0 from source at `.`
Bundle complete! 8 Gemfile dependencies, 13 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

I've made sure to delete worf locally, before running the above.

I wonder what causes the problem :thinking:.

**Comment by 64kramsystem** [comment]
Shot in the dark: what's your Rubygems version?

[This Rubygems PR](https://github.com/rubygems/rubygems/pull/4224) fixes this problem.

**Comment by mohsen-alizadeh** [comment]
Great, checked with rubygems `3.2.28` and worked fine.
