### ISSUE TITLE
Handle Gemfile.lock

### ISSUE THREAD

**Issue by 64kramsystem** [tenderlove/tenderjit#6]
Right now, the Gemfile.lock is neither in the SCM, nor in the .gitignore file, so it's somewhat easy to accidentlly add it (as it's required, for example when running the test suite).

Due to the library nature of the project, I think that it should be put in the .gitignore. As alternative, devs can add it to the local repository ignore list, but I think the former option makes more sense.

I don't have experience with a large number of projects though, so feel free to close straight away if this doesn't make sense :grin:

**Comment by tenderlove** [comment]
Ya, I think we should put it in the `.gitignore`.  I'll add it!
