### ISSUE TITLE
Getting "cannot load such file -- tenderjit/ruby/e6c9f/structs"

### ISSUE THREAD

**Issue by jenko** [tenderlove/tenderjit#9]
Successfully installed the gem, but getting the following when I issue "require 'tenderjit'"

`irb
3.0.2 :001 > require 'tenderjit'
<internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- **tenderjit/ruby/e6c9f/structs (LoadError)**
        from <internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jenko/.rvm/gems/ruby-3.0.2/gems/tenderjit-1.0.0/lib/tenderjit/ruby.rb:8:in `<top (required)>'
        from <internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jenko/.rvm/gems/ruby-3.0.2/gems/tenderjit-1.0.0/lib/tenderjit.rb:3:in `<top (required)>'
        from <internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from (irb):1:in `<main>'
        from /home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /home/jenko/.rvm/rubies/ruby-3.0.2/bin/irb:23:in `load'
        from /home/jenko/.rvm/rubies/ruby-3.0.2/bin/irb:23:in `<main>'
<internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- tenderjit (LoadError)
        from <internal:/home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from (irb):1:in `<main>'
        from /home/jenko/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /home/jenko/.rvm/rubies/ruby-3.0.2/bin/irb:23:in `load'
        from /home/jenko/.rvm/rubies/ruby-3.0.2/bin/irb:23:in `<main>'
`

**Comment by tenderlove** [comment]
I will update the documentation, but you can't install TenderJIT as a gem right now.  You can only do dev work from the main repository.

You should be able to clone the repo then do `rake test`.  It will run a `compile` step which generates the files you need.

**Comment by jenko** [comment]
Ok, thanks for the reply.
